"""Broker estimate comparison

Revision ID: acd4eb4b9a8d
Revises: b00b1c780eee
Create Date: 2025-12-08 22:05:29.246155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd4eb4b9a8d'
down_revision = 'b00b1c780eee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

